/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Menu.menuKasir;
import Menu.menuOwner;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.koneksiDB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Random;
import javax.swing.UIManager;
import koneksi.SessionManager;
import koneksi.sessionRole;
/**
 *
 * @author user
 */
public class formLoginManual extends javax.swing.JFrame {

    /**
     * Creates new form formLoginManual
     */
    public ResultSet rs;
    private final Connection conn;
    public formLoginManual() {
        initComponents();
        conn = koneksiDB.BukaKoneksi();
        hidePass.setVisible(false);
        
        txtUsername.addActionListener(e -> LoginProses());
        txtPass.addActionListener(e -> LoginProses());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnUsername = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtPass = new javax.swing.JPasswordField();
        showPass = new javax.swing.JLabel();
        hidePass = new javax.swing.JLabel();
        roundedPanel1 = new customComponen.RoundedPanel();
        btnLogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnFormRFID = new javax.swing.JLabel();
        btnLupaPassword = new javax.swing.JLabel();
        bgUtama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnUsername.setBackground(new java.awt.Color(255, 255, 255));

        txtUsername.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setText("Username");
        txtUsername.setBorder(null);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnUsernameLayout = new javax.swing.GroupLayout(pnUsername);
        pnUsername.setLayout(pnUsernameLayout);
        pnUsernameLayout.setHorizontalGroup(
            pnUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnUsernameLayout.setVerticalGroup(
            pnUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pnUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 370, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtPass.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setText("Password");
        txtPass.setBorder(null);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });

        showPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye_17347061 (1).png"))); // NOI18N
        showPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPassMouseClicked(evt);
            }
        });

        hidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/interface_13741491 (1).png"))); // NOI18N
        hidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidePassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(showPass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 326, Short.MAX_VALUE)
                    .addComponent(hidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass)
                    .addComponent(showPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 380, 60));

        roundedPanel1.setBackground(new java.awt.Color(70, 155, 126));
        roundedPanel1.setCornerRadius(40);

        btnLogin.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("                           LOGIN");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 470, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnFormRFID.setText("Login menggunkan RFID dan absensi");
        btnFormRFID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFormRFIDMouseClicked(evt);
            }
        });

        btnLupaPassword.setText("Lupa Password");
        btnLupaPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLupaPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(btnFormRFID)
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnLupaPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFormRFID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLupaPassword)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, 320, 60));

        bgUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login #2 manual.png"))); // NOI18N
        jPanel2.add(bgUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 960));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormRFIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormRFIDMouseClicked
        login rfid = new login();
        rfid.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFormRFIDMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
         LoginProses();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        String username= txtUsername.getText();
        if(username.equals("Username")){
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        String username = txtUsername.getText();
        if(username.equals("")||username.equals("Username")){
            txtUsername.setText("Username");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        String pass = txtPass.getText();
        if(pass.equals("Password")){
            txtPass.setText("");
        }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        String pass = txtPass.getText();
        if(pass.equals("")||pass.equals("Password")){
            txtPass.setText("Password");
        }
    }//GEN-LAST:event_txtPassFocusLost

    private void showPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassMouseClicked
        showPass.setVisible(false);
        hidePass.setVisible(true);
        txtPass.setEchoChar((char)0);
       
    }//GEN-LAST:event_showPassMouseClicked

    private void hidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePassMouseClicked
        showPass.setVisible(true);
        hidePass.setVisible(false);
        txtPass.setEchoChar('*');
        

    }//GEN-LAST:event_hidePassMouseClicked

    private void btnLupaPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLupaPasswordMouseClicked
        JOptionPane.showMessageDialog(this, "Silahkan hubungi owner");
    }//GEN-LAST:event_btnLupaPasswordMouseClicked
     private String tentukanStatusPresensi(LocalTime waktuReal) {
        LocalTime waktuSekarang = LocalTime.now();
        System.out.println("Waktu Sekarang: " + waktuSekarang);
        
        if (waktuSekarang.isBefore(LocalTime.of(9, 0))) {
               return "masuk"; // Hadir tepat waktu (antara 08:00 - 08:59)
           } else if (waktuSekarang.isBefore(LocalTime.of(15, 0))) {
               return "masuk"; // Terlambat (antara 09:00 - 14:59)
           } else {
               return "pulang"; 
           }
    }
    
     private void simpanPresensi(String id_user, String status) {
        String idAbsensi = "AB-" + String.format("%05d", new Random().nextInt(99999));

        String sql = "INSERT INTO absensi (id_user, status, waktu_absen, tanggal,id_absensi) VALUES (?, ?, ?, ?,?)";

        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, id_user);
            st.setString(2, status);
            st.setTime(3, Time.valueOf(LocalTime.now())); // Waktu sekarang
            st.setDate(4, Date.valueOf(LocalDate.now())); // Tanggal sekarang
            st.setString(5, idAbsensi);
            st.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal menyimpan presensi!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    
    }
      private boolean mengecekPresensi(String idUser, String status){
          String sql ="SELECT COUNT(*) FROM absensi WHERE id_user = ? AND status = ? AND tanggal = CURDATE()";
          try (PreparedStatement st = conn.prepareStatement(sql)){
              st.setString(1, idUser);
              st.setString(2, status);
              ResultSet rs = st.executeQuery();
              if(rs.next()){
                  return rs.getInt(1)>0;
              }
          } catch (Exception e) {
              e.printStackTrace();
          }
          return false;
    }
      private void LoginProses(){
            try {
            String sql ="SELECT * FROM pengguna WHERE id_user = '"+txtUsername.getText()+"' AND password = '"+txtPass.getText()+"';";
            // menentukan login sebagai owner atau kasir
            try(PreparedStatement st = conn.prepareStatement(sql)){
                 rs = st.executeQuery(sql);
                                 
                if (rs.next()) {
                    String nama= rs.getString("nama");
                    String role = rs.getString("role");
                    String idUser = rs.getString("id_user");
                    SessionManager.setNamaPengguna(nama);
                    sessionRole.setRolePengguna(role);
                    SessionManager.setIdUser(idUser);
                    if (txtUsername.getText().equals(rs.getString("id_user"))&&txtPass.getText().equals(rs.getString("password"))&&rs.getString("role").equals("owner")) {
                        menuOwner owner = new menuOwner();
                        owner.setVisible(true);
                        dispose();
                    }else if(txtUsername.getText().equals(rs.getString("id_user"))&&txtPass.getText().equals(rs.getString("password"))&&rs.getString("role").equals("kasir")){
                         LocalTime waktuReal = LocalTime.now();
                    String status = tentukanStatusPresensi(waktuReal);
                    if (status.equals("masuk")) {
                        if (!mengecekPresensi(idUser, "masuk")) {
                            simpanPresensi(idUser, status);
                            JOptionPane.showMessageDialog(this, "presensi masuk berhasil");
                            
                        }
                    }else if(status.equals("pulang")){
                        if (!mengecekPresensi(idUser, "pulang")) {
                            simpanPresensi(idUser, status);
                            JOptionPane.showMessageDialog(this, "presensi pulang berhasil");
                        }
                    }
                    new menuKasir().setVisible(true);
                    dispose();
                        menuKasir kasir = new  menuKasir();
                        kasir.setVisible(true);
                        dispose();
                    } 
                }else{
                    JOptionPane.showMessageDialog(null,"username dan password anda salah");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "username tidak terdaftar silahkan hubungi owner");
        }
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLoginManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLoginManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLoginManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLoginManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try {
    UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLoginManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgUtama;
    private javax.swing.JLabel btnFormRFID;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnLupaPassword;
    private javax.swing.JLabel hidePass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnUsername;
    private customComponen.RoundedPanel roundedPanel1;
    private javax.swing.JLabel showPass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
