/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import formMenu.formDashboard;
import formMenu.formBarang;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import koneksi.SessionManager;
import koneksi.sessionRole;
import koneksi.koneksiDB;
import java.sql.*;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author user
 */
public class menuKasir extends javax.swing.JFrame {
private JPanel selectedPanel = null;
private JPanel selectedKlik = null;

    private Connection conn;
    public menuKasir() {
        initComponents();
        conn = koneksiDB.BukaKoneksi();
        lbNama.setText( SessionManager.getNamaPengguna());
        lbRole.setText(sessionRole.getRolePengguna());
        String[] data = getStatusAbsensiHariIni(SessionManager.getIdUser());

       // lblJam.setText("Absensi Masuk: " + data[0]);
        //status.setText("Status: " + data[1]);
        LocalDate hariIni = LocalDate.now();
        //lblTanggal.setText("tanggal"+hariIni);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnKiri = new javax.swing.JPanel();
        roundedPanel1 = new customComponen.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        pnTransaksi = new customComponen.RoundedPanel();
        jLabel4 = new javax.swing.JLabel();
        btnTransaki = new javax.swing.JLabel();
        pnKlik6 = new javax.swing.JPanel();
        pn_kanan = new javax.swing.JPanel();
        pnBaratas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel2 = new customComponen.RoundedPanel();
        lbNama = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        pnKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnKiri.setBackground(new java.awt.Color(70, 155, 126));
        pnKiri.setPreferredSize(new java.awt.Dimension(221, 783));

        roundedPanel1.setBackground(new java.awt.Color(70, 155, 126));
        roundedPanel1.setCornerRadius(45);
        roundedPanel1.setPreferredSize(new java.awt.Dimension(199, 780));
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/company (1) (1).png"))); // NOI18N
        roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        pnTransaksi.setBackground(new java.awt.Color(70, 155, 126));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/orders icon.png"))); // NOI18N

        btnTransaki.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaki.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnTransaki.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaki.setText("Transaksi");
        btnTransaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransakiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransakiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransakiMouseExited(evt);
            }
        });

        pnKlik6.setBackground(new java.awt.Color(70, 155, 126));

        javax.swing.GroupLayout pnKlik6Layout = new javax.swing.GroupLayout(pnKlik6);
        pnKlik6.setLayout(pnKlik6Layout);
        pnKlik6Layout.setHorizontalGroup(
            pnKlik6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnKlik6Layout.setVerticalGroup(
            pnKlik6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTransaksiLayout = new javax.swing.GroupLayout(pnTransaksi);
        pnTransaksi.setLayout(pnTransaksiLayout);
        pnTransaksiLayout.setHorizontalGroup(
            pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKlik6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransaki, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTransaksiLayout.setVerticalGroup(
            pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTransaksiLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKlik6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        roundedPanel1.add(pnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        javax.swing.GroupLayout pnKiriLayout = new javax.swing.GroupLayout(pnKiri);
        pnKiri.setLayout(pnKiriLayout);
        pnKiriLayout.setHorizontalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );
        pnKiriLayout.setVerticalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );

        jPanel2.add(pnKiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(70, 155, 126));
        pn_kanan.setPreferredSize(new java.awt.Dimension(1134, 960));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pnBaratas.setBackground(new java.awt.Color(238, 238, 238));
        pnBaratas.setPreferredSize(new java.awt.Dimension(1219, 75));
        pnBaratas.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNama.setForeground(new java.awt.Color(51, 51, 51));
        lbNama.setText("NAMA");

        lbRole.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbRole.setForeground(new java.awt.Color(51, 51, 51));
        lbRole.setText("ROLE");

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addComponent(lbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRole)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(997, Short.MAX_VALUE)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBaratas.add(jPanel1, java.awt.BorderLayout.CENTER);

        pn_kanan.add(pnBaratas, java.awt.BorderLayout.PAGE_START);

        pnKonten.setBackground(new java.awt.Color(238, 238, 238));
        pnKonten.setLayout(new java.awt.BorderLayout());
        pn_kanan.add(pnKonten, java.awt.BorderLayout.CENTER);

        jPanel2.add(pn_kanan, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransakiMouseClicked
        if (selectedPanel != null && selectedPanel != pnTransaksi) {
    selectedPanel.setBackground(new Color(70,155,126));
    
    }
        if (selectedKlik != null && selectedKlik != pnKlik6) {
            selectedKlik.setBackground(new Color(70,155,126)); // Warna default
        }
    // Set panel aktif
    pnKlik6.setBackground(new Color(217,217,217));
    pnTransaksi.setBackground(new Color(50, 85, 75));
    selectedPanel = pnTransaksi; 
    selectedKlik = pnKlik6;

    // Panggil panel laporan harian
    pnKonten.removeAll();
    pnKonten.add(new formBarang());
    pnKonten.repaint();
    pnKonten.revalidate();
    }//GEN-LAST:event_btnTransakiMouseClicked

    private void btnTransakiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransakiMouseEntered
        pnTransaksi.setBackground(new Color(50, 85, 75));
        pnKlik6.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btnTransakiMouseEntered

    private void btnTransakiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransakiMouseExited
         if (selectedPanel != pnTransaksi) {
        pnTransaksi.setBackground(new Color(70,155,126));
        pnKlik6.setBackground(new Color(70,155,126));
        }
    }//GEN-LAST:event_btnTransakiMouseExited
    public String[] getStatusAbsensiHariIni(String idUser) {
        String[] hasil = new String[2]; // hasil[0] = jam masuk, hasil[1] = status telat/tepat waktu
        LocalDate today = LocalDate.now();

        try {
            String sql = "SELECT waktu_absen, status FROM absensi WHERE id_user = ? AND tanggal = ? AND status = 'masuk'";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idUser);
            ps.setDate(2, Date.valueOf(today));
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Time jamMasuk = rs.getTime("waktu_absen");
                String statusDB = rs.getString("status");

                LocalTime waktuMasuk = jamMasuk.toLocalTime();
                hasil[0] = waktuMasuk.format(DateTimeFormatter.ofPattern("HH:mm"));

                LocalTime jamTepat = LocalTime.of(8, 0);
                if (waktuMasuk.isAfter(jamTepat)) {
                   long totalMenitTelat = Duration.between(jamTepat, waktuMasuk).toMinutes();
                    long jam = totalMenitTelat / 60;
                    long menit = totalMenitTelat % 60;

                    if (jam > 0) {
                        hasil[1] = "Terlambat " + jam + " jam " + menit + " menit";
                    } else {
                        hasil[1] = "Terlambat " + menit + " menit";
                    }
                } else {
                    hasil[1] = "Tepat Waktu";
                }
            } else {
                hasil[0] = "-";
                hasil[1] = "Belum Absen Masuk";
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return hasil;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        try {
    UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnTransaki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbRole;
    private javax.swing.JPanel pnBaratas;
    private javax.swing.JPanel pnKiri;
    private javax.swing.JPanel pnKlik6;
    private javax.swing.JPanel pnKonten;
    private customComponen.RoundedPanel pnTransaksi;
    private javax.swing.JPanel pn_kanan;
    private customComponen.RoundedPanel roundedPanel1;
    private customComponen.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
