/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import formMenu.StokPupuk;
import formMenu.formDashboard;
import formMenu.formBarang;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import koneksi.SessionManager;
import koneksi.sessionRole;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import koneksi.koneksiDB;

/**
 *
 * @author user
 */
public class menuOwner extends javax.swing.JFrame {
private JPanel selectedPanel = null;
private JPanel selectedKlik = null;

    private Connection conn;
    public menuOwner() {
        initComponents();
        conn = koneksiDB.BukaKoneksi();
        lbNama.setText( SessionManager.getNamaPengguna());
        lbRole.setText(sessionRole.getRolePengguna());
        
        btnNotif.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        tampilkanNotifikasi();
    }
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnKiri = new javax.swing.JPanel();
        roundedPanel1 = new customComponen.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        pnDashboard = new customComponen.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        pnKlik7 = new javax.swing.JPanel();
        pnTransaksi = new customComponen.RoundedPanel();
        jLabel4 = new javax.swing.JLabel();
        btnTransaki = new javax.swing.JLabel();
        pnKlik6 = new javax.swing.JPanel();
        pnBarang = new customComponen.RoundedPanel();
        jLabel5 = new javax.swing.JLabel();
        btnBarang = new javax.swing.JLabel();
        pnKlik3 = new javax.swing.JPanel();
        pnLaporan = new customComponen.RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JLabel();
        pnKlik5 = new javax.swing.JPanel();
        pnAkun = new customComponen.RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAkun = new javax.swing.JLabel();
        pnKlik4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pnBaratas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel2 = new customComponen.RoundedPanel();
        lbNama = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        btnNotif = new javax.swing.JLabel();
        pnKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnKiri.setBackground(new java.awt.Color(70, 155, 126));
        pnKiri.setPreferredSize(new java.awt.Dimension(221, 783));

        roundedPanel1.setBackground(new java.awt.Color(70, 155, 126));
        roundedPanel1.setCornerRadius(45);
        roundedPanel1.setPreferredSize(new java.awt.Dimension(199, 780));
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/company (1) (1).png"))); // NOI18N
        roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        pnDashboard.setBackground(new java.awt.Color(70, 155, 126));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dashboard icon_waifu2x_art_noise3.png"))); // NOI18N

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });

        pnKlik7.setBackground(new java.awt.Color(70, 155, 126));

        javax.swing.GroupLayout pnKlik7Layout = new javax.swing.GroupLayout(pnKlik7);
        pnKlik7.setLayout(pnKlik7Layout);
        pnKlik7Layout.setHorizontalGroup(
            pnKlik7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnKlik7Layout.setVerticalGroup(
            pnKlik7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnDashboardLayout = new javax.swing.GroupLayout(pnDashboard);
        pnDashboard.setLayout(pnDashboardLayout);
        pnDashboardLayout.setHorizontalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKlik7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnDashboardLayout.setVerticalGroup(
            pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDashboardLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(pnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDashboardLayout.createSequentialGroup()
                        .addComponent(pnKlik7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDashboardLayout.createSequentialGroup()
                        .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel1.add(pnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 127, 230, 60));

        pnTransaksi.setBackground(new java.awt.Color(70, 155, 126));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/orders icon.png"))); // NOI18N

        btnTransaki.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaki.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnTransaki.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaki.setText("Transaksi");
        btnTransaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransakiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransakiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransakiMouseExited(evt);
            }
        });

        pnKlik6.setBackground(new java.awt.Color(70, 155, 126));

        javax.swing.GroupLayout pnKlik6Layout = new javax.swing.GroupLayout(pnKlik6);
        pnKlik6.setLayout(pnKlik6Layout);
        pnKlik6Layout.setHorizontalGroup(
            pnKlik6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnKlik6Layout.setVerticalGroup(
            pnKlik6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTransaksiLayout = new javax.swing.GroupLayout(pnTransaksi);
        pnTransaksi.setLayout(pnTransaksiLayout);
        pnTransaksiLayout.setHorizontalGroup(
            pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKlik6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransaki, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTransaksiLayout.setVerticalGroup(
            pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTransaksiLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKlik6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        roundedPanel1.add(pnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 220, 60));

        pnBarang.setBackground(new java.awt.Color(70, 155, 126));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/inventory icon.png"))); // NOI18N

        btnBarang.setBackground(new java.awt.Color(255, 255, 255));
        btnBarang.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnBarang.setText("Barang");
        btnBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBarangMouseExited(evt);
            }
        });

        pnKlik3.setBackground(new java.awt.Color(70, 155, 126));

        javax.swing.GroupLayout pnKlik3Layout = new javax.swing.GroupLayout(pnKlik3);
        pnKlik3.setLayout(pnKlik3Layout);
        pnKlik3Layout.setHorizontalGroup(
            pnKlik3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnKlik3Layout.setVerticalGroup(
            pnKlik3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBarangLayout = new javax.swing.GroupLayout(pnBarang);
        pnBarang.setLayout(pnBarangLayout);
        pnBarangLayout.setHorizontalGroup(
            pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKlik3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBarangLayout.setVerticalGroup(
            pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBarangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnKlik3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        roundedPanel1.add(pnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 60));

        pnLaporan.setBackground(new java.awt.Color(70, 155, 126));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/resport icon.png"))); // NOI18N

        btnLaporan.setBackground(new java.awt.Color(255, 255, 255));
        btnLaporan.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("Laporan");
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        pnKlik5.setBackground(new java.awt.Color(70, 155, 126));

        javax.swing.GroupLayout pnKlik5Layout = new javax.swing.GroupLayout(pnKlik5);
        pnKlik5.setLayout(pnKlik5Layout);
        pnKlik5Layout.setHorizontalGroup(
            pnKlik5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnKlik5Layout.setVerticalGroup(
            pnKlik5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnLaporanLayout = new javax.swing.GroupLayout(pnLaporan);
        pnLaporan.setLayout(pnLaporanLayout);
        pnLaporanLayout.setHorizontalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKlik5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnLaporanLayout.setVerticalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLaporanLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(pnKlik5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        roundedPanel1.add(pnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 70));

        pnAkun.setBackground(new java.awt.Color(70, 155, 126));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account icon.png"))); // NOI18N

        btnAkun.setBackground(new java.awt.Color(255, 255, 255));
        btnAkun.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnAkun.setForeground(new java.awt.Color(255, 255, 255));
        btnAkun.setText("Akun");
        btnAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAkunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAkunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAkunMouseExited(evt);
            }
        });

        pnKlik4.setBackground(new java.awt.Color(70, 155, 126));

        javax.swing.GroupLayout pnKlik4Layout = new javax.swing.GroupLayout(pnKlik4);
        pnKlik4.setLayout(pnKlik4Layout);
        pnKlik4Layout.setHorizontalGroup(
            pnKlik4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnKlik4Layout.setVerticalGroup(
            pnKlik4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnAkunLayout = new javax.swing.GroupLayout(pnAkun);
        pnAkun.setLayout(pnAkunLayout);
        pnAkunLayout.setHorizontalGroup(
            pnAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnKlik4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnAkunLayout.setVerticalGroup(
            pnAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAkunLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(pnAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKlik4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAkunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundedPanel1.add(pnAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        roundedPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("       Logout");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        roundedPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 140, 50));

        javax.swing.GroupLayout pnKiriLayout = new javax.swing.GroupLayout(pnKiri);
        pnKiri.setLayout(pnKiriLayout);
        pnKiriLayout.setHorizontalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        pnKiriLayout.setVerticalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );

        jPanel2.add(pnKiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(70, 155, 126));
        pn_kanan.setPreferredSize(new java.awt.Dimension(1134, 960));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pnBaratas.setBackground(new java.awt.Color(238, 238, 238));
        pnBaratas.setPreferredSize(new java.awt.Dimension(1219, 75));
        pnBaratas.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNama.setForeground(new java.awt.Color(51, 51, 51));
        lbNama.setText("NAMA");

        lbRole.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbRole.setForeground(new java.awt.Color(51, 51, 51));
        lbRole.setText("ROLE");

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNama, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(lbRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addComponent(lbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbRole)
                .addContainerGap())
        );

        btnNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/subscribe_8448790.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1006, Short.MAX_VALUE)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnNotif)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnBaratas.add(jPanel1, java.awt.BorderLayout.CENTER);

        pn_kanan.add(pnBaratas, java.awt.BorderLayout.PAGE_START);

        pnKonten.setBackground(new java.awt.Color(238, 238, 238));
        pnKonten.setLayout(new java.awt.BorderLayout());
        pn_kanan.add(pnKonten, java.awt.BorderLayout.CENTER);

        jPanel2.add(pn_kanan, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
         pnDashboard.setBackground(new Color(50, 85, 75));
         pnKlik7.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
    if (selectedPanel != null && selectedPanel != pnDashboard) {
    selectedPanel.setBackground(new Color(70,155,126)); // Warna default
    }
        if (selectedKlik != null && selectedKlik != pnKlik7) {
            selectedKlik.setBackground(new Color(70,155,126)); // Warna default
        }

    // Set panel aktif
    pnKlik7.setBackground(new Color(217,217,217));
    pnDashboard.setBackground(new Color(50, 85, 75));
    selectedPanel = pnDashboard; 
    selectedKlik = pnKlik7;

    // Panggil panel laporan harian
    pnKonten.removeAll();
    pnKonten.add(new formDashboard());
    pnKonten.repaint();
    pnKonten.revalidate();
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
         if (selectedPanel != pnDashboard) {
        pnDashboard.setBackground(new Color(70,155,126));
        pnKlik7.setBackground(new Color(70,155,126));
        
    }
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnTransakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransakiMouseClicked
        if (selectedPanel != null && selectedPanel != pnTransaksi) {
    selectedPanel.setBackground(new Color(70,155,126));
    
    }
        if (selectedKlik != null && selectedKlik != pnKlik6) {
            selectedKlik.setBackground(new Color(70,155,126)); // Warna default
        }
    // Set panel aktif
    pnKlik6.setBackground(new Color(217,217,217));
    pnTransaksi.setBackground(new Color(50, 85, 75));
    selectedPanel = pnTransaksi; 
    selectedKlik = pnKlik6;

    // Panggil panel laporan harian
    pnKonten.removeAll();
    pnKonten.add(new formBarang());
    pnKonten.repaint();
    pnKonten.revalidate();
    }//GEN-LAST:event_btnTransakiMouseClicked

    private void btnTransakiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransakiMouseEntered
        pnTransaksi.setBackground(new Color(50, 85, 75));
        pnKlik6.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btnTransakiMouseEntered

    private void btnTransakiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransakiMouseExited
         if (selectedPanel != pnTransaksi) {
        pnTransaksi.setBackground(new Color(70,155,126));
        pnKlik6.setBackground(new Color(70,155,126));
        }
    }//GEN-LAST:event_btnTransakiMouseExited

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
         if (selectedPanel != null && selectedPanel != pnLaporan ) {
            selectedPanel.setBackground(new Color(70,155,126));
            
        }
         if (selectedKlik != null && selectedKlik != pnKlik5) {
            selectedKlik.setBackground(new Color(70,155,126)); // Warna default
        }
        pnKlik5.setBackground(new Color(217,217,217));
        pnLaporan.setBackground(new Color(50, 85, 75));
        selectedPanel = pnLaporan;
        selectedKlik = pnKlik5;

        pnKonten.removeAll();
        pnKonten.add(new StokPupuk());
        pnKonten.repaint();
        pnKonten.revalidate();
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
         pnLaporan.setBackground(new Color(50, 85, 75));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        if (selectedPanel != pnLaporan) {
             pnLaporan.setBackground(new Color(70,155,126));
            pnKlik5.setBackground(new Color(70,155,126));
        }
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAkunMouseClicked
        if (selectedPanel != null && selectedPanel != pnAkun ) {
            selectedPanel.setBackground(new Color(70,155,126));
            
        }
         if (selectedKlik != null && selectedKlik != pnKlik4) {
            selectedKlik.setBackground(new Color(70,155,126)); // Warna default
        }
        pnKlik4.setBackground(new Color(217,217,217));
        pnAkun.setBackground(new Color(50, 85, 75));
        selectedPanel = pnAkun;
        selectedKlik = pnKlik4;

        pnKonten.removeAll();
        pnKonten.add(new formBarang());
        pnKonten.repaint();
        pnKonten.revalidate();
    }//GEN-LAST:event_btnAkunMouseClicked

    private void btnAkunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAkunMouseEntered
        pnAkun.setBackground(new Color(50, 85, 75));
        pnKlik4.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btnAkunMouseEntered

    private void btnAkunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAkunMouseExited
        if (selectedPanel != pnAkun) {
             pnAkun.setBackground(new Color(70,155,126));
            pnKlik4.setBackground(new Color(70,155,126));
        }
    }//GEN-LAST:event_btnAkunMouseExited

    private void btnBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseExited
        if (selectedPanel != pnBarang ) {
            pnBarang.setBackground(new Color(70,155,126));
            pnKlik3.setBackground(new Color(70,155,126));
        }
    }//GEN-LAST:event_btnBarangMouseExited

    private void btnBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseEntered
        pnBarang.setBackground(new Color(50, 85, 75));
        pnKlik3.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_btnBarangMouseEntered

    private void btnBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseClicked
        if (selectedPanel != null && selectedPanel != pnBarang ) {
            selectedPanel.setBackground(new Color(70,155,126));
            
        }
         if (selectedKlik != null && selectedKlik != pnKlik3) {
            selectedKlik.setBackground(new Color(70,155,126)); // Warna default
        }
        pnKlik3.setBackground(new Color(217,217,217));
        pnBarang.setBackground(new Color(50, 85, 75));
        selectedPanel = pnBarang;
        selectedKlik = pnKlik3;

        pnKonten.removeAll();
        pnKonten.add(new formBarang());
        pnKonten.repaint();
        pnKonten.revalidate();
    }//GEN-LAST:event_btnBarangMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
            dispose();
            //kembali ke halaman login
            formLoginManual logout = new formLoginManual();
            logout.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        try {
    UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAkun;
    private javax.swing.JLabel btnBarang;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnLaporan;
    private javax.swing.JLabel btnNotif;
    private javax.swing.JLabel btnTransaki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbRole;
    private customComponen.RoundedPanel pnAkun;
    private customComponen.RoundedPanel pnBarang;
    private javax.swing.JPanel pnBaratas;
    private customComponen.RoundedPanel pnDashboard;
    private javax.swing.JPanel pnKiri;
    private javax.swing.JPanel pnKlik3;
    private javax.swing.JPanel pnKlik4;
    private javax.swing.JPanel pnKlik5;
    private javax.swing.JPanel pnKlik6;
    private javax.swing.JPanel pnKlik7;
    private javax.swing.JPanel pnKonten;
    private customComponen.RoundedPanel pnLaporan;
    private customComponen.RoundedPanel pnTransaksi;
    private javax.swing.JPanel pn_kanan;
    private customComponen.RoundedPanel roundedPanel1;
    private customComponen.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
private void tampilkanNotifikasi() {
    StringBuilder notif = new StringBuilder();

    try {
        // Cek stok menipis
        String sqlStok = "SELECT nama_pupuk, stock FROM pupuk WHERE stock <= 20";
        PreparedStatement stStok = conn.prepareStatement(sqlStok);
        ResultSet rsStok = stStok.executeQuery();

        while (rsStok.next()) {
            String nama = rsStok.getString("nama_pupuk");
            int stok = rsStok.getInt("stock");
            notif.append("Stok menipis: ").append(nama).append(" (").append(stok).append(" sak)\n");
        }

        // Cek produk kadaluarsa (opsional)
        String sqlExp = "SELECT nama_pupuk, tgl_expired FROM pupuk WHERE tgl_expired <= CURDATE()";
        PreparedStatement stExp = conn.prepareStatement(sqlExp);
        ResultSet rsExp = stExp.executeQuery();

        while (rsExp.next()) {
            String nama = rsExp.getString("nama_pupuk");
            String tgl = rsExp.getString("tgl_expired");
            notif.append("Kadaluarsa: ").append(nama).append(" (").append(tgl).append(")\n"); 
        }

        if (notif.length() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada notifikasi untuk saat ini.", "Notifikasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JTextArea area = new JTextArea(notif.toString());
            area.setEditable(false);
            JOptionPane.showMessageDialog(this, new JScrollPane(area), "Notifikasi", JOptionPane.WARNING_MESSAGE);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat notifikasi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

}
